In [391]:
import contractions
from bs4 import BeautifulSoup
import requests

# Phase 1: Data Retrieval

In [393]:
URL = "https://www.goodreads.com/book/show/220239083-a-marriage-at-sea"
page = requests.get(URL)

print(page.text)

In [395]:
page_text = page.text

In [396]:
soup = BeautifulSoup(page_text, 'html.parser')

In [397]:
strip_list = []

In [398]:
all_comments = soup.find_all('div', class_="TruncatedContent__text TruncatedContent__text--large")
for comments in all_comments:
  #print(comments.text.strip())
  strip_list.append(comments.text.strip())

# Phase 2: Data Cleaning

In [400]:
# removing first "review", as it is a description
strip_list.pop(0)

'“A beautiful meditation on endurance, codependence, and the power of love. A dazzling book.” – Patrick Radden KeefeThe electrifying true story of a young couple shipwrecked at a mind-blowing tale of obsession, survival, and partnership stretched to its limits.Maurice and Maralyn make an odd couple. He’s a loner, awkward and obsessive; she’s charismatic and ambitious. But they share a horror of wasting their lives. And they dream – as we all dream – of running away from it all. What if they quit their jobs, sold their house, bought a boat, and sailed away?Most of us begin and end with the daydream. But Maurice began to study nautical navigation. Maralyn made detailed lists of provisions. And in June 1972, they set sail. For nearly a year all went well, until deep in the Pacific, a breaching whale knocked a hole in their boat and it sank beneath the waves.What ensues is a jaw-dropping fight to survive in the wild ocean, with little hope of rescue. Alone together for months in a tiny rub

In [401]:
# removing the review that has a foreign language within in it.
# strip_list.pop(20)
# strip_list.pop(21)
# strip_list.pop(22)

del strip_list[26]
del strip_list[24]

reviewing the list once again

In [403]:
for i in strip_list:
  print(i)

“You only truly possess that which you cannot lose in a shipwreck.” ‎― أبو حامد الغزالي This is the amazing true story of Maurice and Maralyn Bailey’s 118 days adrift in the middle of the Pacific Ocean.Maurice and Maralyn Bailey were stifled with their lives, they had a perfectly nice new home, a car and good jobs, but it wasn’t enough, so after much discussion and planning, they sold the house and all their possessions, and left a 1970’s crisis ridden England in their lovely new boat, and set sail for New Zealand. However, things didn’t go according to plan when their boat was struck by a whale, leaving them adrift on a small raft in the middle of the Pacific Ocean.On the face of it, Maurice and Maralyn were an unlikely couple - Maurice was awkward, uncomfortable in other people’s company and he was extremely cautious, whilst Maralyn was charismatic and up for any challenge, and although they both wanted to be free to travel, to escape, unburdened by the nine to five and expectations 

In [404]:
# converting each string into a lowercase
def conversions(strip_list):
  temp_list = []
  for i in strip_list:
    c_lowered = i.lower()
    temp_list.append(c_lowered)
  return temp_list

In [405]:
strip_list = conversions(strip_list)

verification of the lowercasing process

In [407]:
print("\n \n This is the new list: ")
for i in strip_list:
  print(i)


 
 This is the new list: 
“you only truly possess that which you cannot lose in a shipwreck.” ‎― أبو حامد الغزالي this is the amazing true story of maurice and maralyn bailey’s 118 days adrift in the middle of the pacific ocean.maurice and maralyn bailey were stifled with their lives, they had a perfectly nice new home, a car and good jobs, but it wasn’t enough, so after much discussion and planning, they sold the house and all their possessions, and left a 1970’s crisis ridden england in their lovely new boat, and set sail for new zealand. however, things didn’t go according to plan when their boat was struck by a whale, leaving them adrift on a small raft in the middle of the pacific ocean.on the face of it, maurice and maralyn were an unlikely couple - maurice was awkward, uncomfortable in other people’s company and he was extremely cautious, whilst maralyn was charismatic and up for any challenge, and although they both wanted to be free to travel, to escape, unburdened by the nin

removing any special character and punctuations

In [409]:
def removing_specialchar(strip_list):
  import string
  translator = str.maketrans('', '', string.punctuation)
  temp_list = []
  for i in strip_list:
    cleaning_strips = i.translate(translator)
    temp_list.append(cleaning_strips)

  return temp_list

In [410]:
# verification of the removing of special characters and punctuation
strip_list = removing_specialchar(strip_list)
strip_list.pop(20)
print(f'Verification Process: ')
counter = 0
for i in strip_list:
    print()
    print(i + "Counter: ", counter)
    counter += 1

Verification Process: 

“you only truly possess that which you cannot lose in a shipwreck” ‎― أبو حامد الغزالي this is the amazing true story of maurice and maralyn bailey’s 118 days adrift in the middle of the pacific oceanmaurice and maralyn bailey were stifled with their lives they had a perfectly nice new home a car and good jobs but it wasn’t enough so after much discussion and planning they sold the house and all their possessions and left a 1970’s crisis ridden england in their lovely new boat and set sail for new zealand however things didn’t go according to plan when their boat was struck by a whale leaving them adrift on a small raft in the middle of the pacific oceanon the face of it maurice and maralyn were an unlikely couple  maurice was awkward uncomfortable in other people’s company and he was extremely cautious whilst maralyn was charismatic and up for any challenge and although they both wanted to be free to travel to escape unburdened by the nine to five and expectati

all special characters and punctuation have been removed.

lastly we will be converting contraction for consistency during our training process

In [413]:
def fix_contractions(strip_list):
  temp_list = []
  for i in strip_list:
    contracted_strip = contractions.fix(i)
    temp_list.append(contracted_strip)

  return temp_list

verification of recontraction

In [415]:
strip_list = fix_contractions(strip_list)

In [416]:
print("Contraction successful? ")
print(strip_list[11])

Contraction successful? 
stopping after about an hour of the audio too dry


the contraction is successful!

In [418]:
# strip_list.pop(20)
len(strip_list)


27

In [419]:
strip_list_labels = [ 'positive', 'negative', 'positive', 'negative', 
                     'positive', 'positive', 'neutral', 
                     'positive', 'negative', 'negative', 'positive', 
                     'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'neutral', 
                     'negative', 'positive', 'negative', 'positive', 'negative', 'negative', 'positive',
                     'negative','negative',
                      ]
print(len(strip_list))
print(len(strip_list_labels))

strip_list_zipped = zip(strip_list, strip_list_labels)
strip_list_dictionary = dict(strip_list_zipped)


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
strip_labels_encoded = le.fit_transform(strip_list_labels)

print(strip_labels_encoded)


27
27
[2 0 2 0 2 2 1 2 0 0 2 0 0 0 2 0 0 1 0 2 0 2 0 0 2 0 0]


In [420]:
# Importing Tfidf from Sklearn

from sklearn.feature_extraction.text import TfidfVectorizer

In [421]:
# Intialize the constructor for the Tfidf class.

tfidf = TfidfVectorizer()

In [422]:
import pandas as pd

tfidf_strips = []

#Executing the string transformation to a matrix of vectors

strip_vector = tfidf.fit_transform(strip_list)
tfidf_strips.append(strip_vector)

view_strip_vector = strip_vector.toarray()
display(view_strip_vector)

#Converting to a pandas DataFrame to make it more readable.

feature_names = tfidf.get_feature_names_out()
Vector_DataFrame = pd.DataFrame(view_strip_vector, columns = feature_names)
display(Vector_DataFrame)

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.06144615, 0.06144615,
        0.06144615],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

100       115       116       117       118        13      1970  \
0   0.000000  0.000000  0.000000  0.000000  0.029222  0.000000  0.047205   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000  0.000000  0.036782  0.000000  0.000000   
10  0.000000  0.000000  0.000000  0.042708  0.029754  0.048064  0.000000   
11  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
13  0.000000  0.024951  0.024951  0.000000  0.000000  0.000000  0.000000   
14  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.059295  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
17  0.000000  0.000000  0.000000  0.161498  0.000000  0.000000  0.000000   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.000000  0.000000  0.000000  0.000000  0.034525  0.000000  0.000000   
20  0.000000  0.000000  0.000000  0.000000  0.080191  0.000000  0.000000   
21  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
22  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
23  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
24  0.000000  0.000000  0.000000  0.000000  0.076077  0.000000  0.000000   
25  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
26  0.000000  0.000000  0.000000  0.000000  0.026405  0.000000  0.000000   

       1970s      1972      1973  ...        𝗔𝗧  𝗠𝗔𝗥𝗥𝗜𝗔𝗚𝗘       𝗦𝗘𝗔      𝘓𝘰𝘷𝘦  \
0   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
4   0.000000  0.089772  0.081785  ...  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
8   0.111957  0.099483  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
10  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
12  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
13  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
14  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
15  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
16  0.000000  0.000000  0.048001  ...  0.000000  0.000000  0.000000  0.000000   
17  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
18  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
19  0.000000  0.000000  0.090297  ...  0.000000  0.000000  0.000000  0.000000   
20  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
21  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
22  0.000000  0.0

In [423]:
from sklearn.model_selection import train_test_split

In [424]:
X_train, X_test, y_train, y_test = train_test_split(strip_vector, strip_labels_encoded, test_size = 0.2, random_state = 42)
from sklearn.preprocessing import LabelEncoder

#le = LabelEncoder()
# y_train_enc = le.fit_transform(y_train)
## y_test_enc = le.transform(y_test)

In [425]:
 from sklearn.linear_model import LogisticRegression

In [426]:
 logistic_regression = LogisticRegression()

In [427]:
 logistic_regression.fit(X_train, y_train)

LogisticRegression()

In [428]:
y_predictions = logistic_regression.predict(X_test)

In [429]:
display(y_predictions)

array([0, 0, 0, 0, 0, 0], dtype=int64)

In [430]:
import numpy as np
unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))


{0: 11, 1: 2, 2: 8}


# Phase 4: Model Performance Measurements

In [432]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Accuracy:", accuracy_score(y_test, y_predictions))
print(classification_report(y_test, y_predictions))
print(confusion_matrix(y_test, y_predictions))


Accuracy: 0.6666666666666666
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         4
           2       0.00      0.00      0.00         2

    accuracy                           0.67         6
   macro avg       0.33      0.50      0.40         6
weighted avg       0.44      0.67      0.53         6

[[4 0]
 [2 0]]


C:\Users\hik\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\hik\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\hik\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
